//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.10 at 02:35:07 PM CET 
//


package bpsim;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bpsim package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NegativeExponentialDistribution_QNAME = new QName("http://www.bpsim.org/schemas/2.0", "NegativeExponentialDistribution");
    private final static QName _BetaDistribution_QNAME = new QName("http://www.bpsim.org/schemas/2.0", "BetaDistribution");
    private final static QName _NormalDistribution_QNAME = new QName("http://www.bpsim.org/schemas/2.0", "NormalDistribution");
    private final static QName _DateTimeParameter_QNAME = new QName("http://www.bpsim.org/schemas/2.0", "DateTimeParameter");
    private final static QName _ExpressionParameter_QNAME = new QName("http://www.bpsim.org/schemas/2.0", "ExpressionParameter");
    private final static QName _DurationParameter_QNAME = new QName("http://www.bpsim.org/schemas/2.0", "DurationParameter");
    private final static QName _WeibullDistribution_QNAME = new QName("http://www.bpsim.org/schemas/2.0", "WeibullDistribution");
    private final static QName _GammaDistribution_QNAME = new QName("http://www.bpsim.org/schemas/2.0", "GammaDistribution");
    private final static QName _BinomialDistribution_QNAME = new QName("http://www.bpsim.org/schemas/2.0", "BinomialDistribution");
    private final static QName _TriangularDistribution_QNAME = new QName("http://www.bpsim.org/schemas/2.0", "TriangularDistribution");
    private final static QName _StringParameter_QNAME = new QName("http://www.bpsim.org/schemas/2.0", "StringParameter");
    private final static QName _UserDistribution_QNAME = new QName("http://www.bpsim.org/schemas/2.0", "UserDistribution");
    private final static QName _PoissonDistribution_QNAME = new QName("http://www.bpsim.org/schemas/2.0", "PoissonDistribution");
    private final static QName _NumericParameter_QNAME = new QName("http://www.bpsim.org/schemas/2.0", "NumericParameter");
    private final static QName _TruncatedNormalDistribution_QNAME = new QName("http://www.bpsim.org/schemas/2.0", "TruncatedNormalDistribution");
    private final static QName _ParameterValue_QNAME = new QName("http://www.bpsim.org/schemas/2.0", "ParameterValue");
    private final static QName _ErlangDistribution_QNAME = new QName("http://www.bpsim.org/schemas/2.0", "ErlangDistribution");
    private final static QName _FloatingParameter_QNAME = new QName("http://www.bpsim.org/schemas/2.0", "FloatingParameter");
    private final static QName _UniformDistribution_QNAME = new QName("http://www.bpsim.org/schemas/2.0", "UniformDistribution");
    private final static QName _EnumParameter_QNAME = new QName("http://www.bpsim.org/schemas/2.0", "EnumParameter");
    private final static QName _LogNormalDistribution_QNAME = new QName("http://www.bpsim.org/schemas/2.0", "LogNormalDistribution");
    private final static QName _BooleanParameter_QNAME = new QName("http://www.bpsim.org/schemas/2.0", "BooleanParameter");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bpsim
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PropertyParameters }
     * 
     */
    public PropertyParameters createPropertyParameters() {
        return new PropertyParameters();
    }

    /**
     * Create an instance of {@link Scenario }
     * 
     */
    public Scenario createScenario() {
        return new Scenario();
    }

    /**
     * Create an instance of {@link PoissonDistribution }
     * 
     */
    public PoissonDistribution createPoissonDistribution() {
        return new PoissonDistribution();
    }

    /**
     * Create an instance of {@link ParameterValue }
     * 
     */
    public ParameterValue createParameterValue() {
        return new ParameterValue();
    }

    /**
     * Create an instance of {@link StringParameter }
     * 
     */
    public StringParameter createStringParameter() {
        return new StringParameter();
    }

    /**
     * Create an instance of {@link UserDistribution }
     * 
     */
    public UserDistribution createUserDistribution() {
        return new UserDistribution();
    }

    /**
     * Create an instance of {@link ErlangDistribution }
     * 
     */
    public ErlangDistribution createErlangDistribution() {
        return new ErlangDistribution();
    }

    /**
     * Create an instance of {@link FloatingParameter }
     * 
     */
    public FloatingParameter createFloatingParameter() {
        return new FloatingParameter();
    }

    /**
     * Create an instance of {@link BPSimData }
     * 
     */
    public BPSimData createBPSimData() {
        return new BPSimData();
    }

    /**
     * Create an instance of {@link NumericParameter }
     * 
     */
    public NumericParameter createNumericParameter() {
        return new NumericParameter();
    }

    /**
     * Create an instance of {@link TruncatedNormalDistribution }
     * 
     */
    public TruncatedNormalDistribution createTruncatedNormalDistribution() {
        return new TruncatedNormalDistribution();
    }

    /**
     * Create an instance of {@link UniformDistribution }
     * 
     */
    public UniformDistribution createUniformDistribution() {
        return new UniformDistribution();
    }

    /**
     * Create an instance of {@link EnumParameter }
     * 
     */
    public EnumParameter createEnumParameter() {
        return new EnumParameter();
    }

    /**
     * Create an instance of {@link UserDistributionDataPoint }
     * 
     */
    public UserDistributionDataPoint createUserDistributionDataPoint() {
        return new UserDistributionDataPoint();
    }

    /**
     * Create an instance of {@link BooleanParameter }
     * 
     */
    public BooleanParameter createBooleanParameter() {
        return new BooleanParameter();
    }

    /**
     * Create an instance of {@link LogNormalDistribution }
     * 
     */
    public LogNormalDistribution createLogNormalDistribution() {
        return new LogNormalDistribution();
    }

    /**
     * Create an instance of {@link BetaDistribution }
     * 
     */
    public BetaDistribution createBetaDistribution() {
        return new BetaDistribution();
    }

    /**
     * Create an instance of {@link NegativeExponentialDistribution }
     * 
     */
    public NegativeExponentialDistribution createNegativeExponentialDistribution() {
        return new NegativeExponentialDistribution();
    }

    /**
     * Create an instance of {@link NormalDistribution }
     * 
     */
    public NormalDistribution createNormalDistribution() {
        return new NormalDistribution();
    }

    /**
     * Create an instance of {@link DateTimeParameter }
     * 
     */
    public DateTimeParameter createDateTimeParameter() {
        return new DateTimeParameter();
    }

    /**
     * Create an instance of {@link ExpressionParameter }
     * 
     */
    public ExpressionParameter createExpressionParameter() {
        return new ExpressionParameter();
    }

    /**
     * Create an instance of {@link DurationParameter }
     * 
     */
    public DurationParameter createDurationParameter() {
        return new DurationParameter();
    }

    /**
     * Create an instance of {@link WeibullDistribution }
     * 
     */
    public WeibullDistribution createWeibullDistribution() {
        return new WeibullDistribution();
    }

    /**
     * Create an instance of {@link BinomialDistribution }
     * 
     */
    public BinomialDistribution createBinomialDistribution() {
        return new BinomialDistribution();
    }

    /**
     * Create an instance of {@link TriangularDistribution }
     * 
     */
    public TriangularDistribution createTriangularDistribution() {
        return new TriangularDistribution();
    }

    /**
     * Create an instance of {@link GammaDistribution }
     * 
     */
    public GammaDistribution createGammaDistribution() {
        return new GammaDistribution();
    }

    /**
     * Create an instance of {@link VendorExtension }
     * 
     */
    public VendorExtension createVendorExtension() {
        return new VendorExtension();
    }

    /**
     * Create an instance of {@link CostParameters }
     * 
     */
    public CostParameters createCostParameters() {
        return new CostParameters();
    }

    /**
     * Create an instance of {@link bpsim.ElementParameters }
     * 
     */
    public bpsim.ElementParameters createElementParameters() {
        return new bpsim.ElementParameters();
    }

    /**
     * Create an instance of {@link Calendar }
     * 
     */
    public Calendar createCalendar() {
        return new Calendar();
    }

    /**
     * Create an instance of {@link ConstantParameter }
     * 
     */
    public ConstantParameter createConstantParameter() {
        return new ConstantParameter();
    }

    /**
     * Create an instance of {@link ResourceParameters }
     * 
     */
    public ResourceParameters createResourceParameters() {
        return new ResourceParameters();
    }

    /**
     * Create an instance of {@link ControlParameters }
     * 
     */
    public ControlParameters createControlParameters() {
        return new ControlParameters();
    }

    /**
     * Create an instance of {@link bpsim.ScenarioParameters }
     * 
     */
    public bpsim.ScenarioParameters createScenarioParameters() {
        return new bpsim.ScenarioParameters();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link DistributionParameter }
     * 
     */
    public DistributionParameter createDistributionParameter() {
        return new DistributionParameter();
    }

    /**
     * Create an instance of {@link PriorityParameters }
     * 
     */
    public PriorityParameters createPriorityParameters() {
        return new PriorityParameters();
    }

    /**
     * Create an instance of {@link TimeParameters }
     * 
     */
    public TimeParameters createTimeParameters() {
        return new TimeParameters();
    }

    /**
     * Create an instance of {@link PropertyParameters.Property }
     * 
     */
    public PropertyParameters.Property createPropertyParametersProperty() {
        return new PropertyParameters.Property();
    }

    /**
     * Create an instance of {@link Scenario.ScenarioParameters }
     * 
     */
    public Scenario.ScenarioParameters createScenarioScenarioParameters() {
        return new Scenario.ScenarioParameters();
    }

    /**
     * Create an instance of {@link Scenario.ElementParameters }
     * 
     */
    public Scenario.ElementParameters createScenarioElementParameters() {
        return new Scenario.ElementParameters();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NegativeExponentialDistribution }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bpsim.org/schemas/2.0", name = "NegativeExponentialDistribution", substitutionHeadNamespace = "http://www.bpsim.org/schemas/2.0", substitutionHeadName = "ParameterValue")
    public JAXBElement<NegativeExponentialDistribution> createNegativeExponentialDistribution(NegativeExponentialDistribution value) {
        return new JAXBElement<NegativeExponentialDistribution>(_NegativeExponentialDistribution_QNAME, NegativeExponentialDistribution.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BetaDistribution }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bpsim.org/schemas/2.0", name = "BetaDistribution", substitutionHeadNamespace = "http://www.bpsim.org/schemas/2.0", substitutionHeadName = "ParameterValue")
    public JAXBElement<BetaDistribution> createBetaDistribution(BetaDistribution value) {
        return new JAXBElement<BetaDistribution>(_BetaDistribution_QNAME, BetaDistribution.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NormalDistribution }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bpsim.org/schemas/2.0", name = "NormalDistribution", substitutionHeadNamespace = "http://www.bpsim.org/schemas/2.0", substitutionHeadName = "ParameterValue")
    public JAXBElement<NormalDistribution> createNormalDistribution(NormalDistribution value) {
        return new JAXBElement<NormalDistribution>(_NormalDistribution_QNAME, NormalDistribution.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateTimeParameter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bpsim.org/schemas/2.0", name = "DateTimeParameter", substitutionHeadNamespace = "http://www.bpsim.org/schemas/2.0", substitutionHeadName = "ParameterValue")
    public JAXBElement<DateTimeParameter> createDateTimeParameter(DateTimeParameter value) {
        return new JAXBElement<DateTimeParameter>(_DateTimeParameter_QNAME, DateTimeParameter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExpressionParameter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bpsim.org/schemas/2.0", name = "ExpressionParameter", substitutionHeadNamespace = "http://www.bpsim.org/schemas/2.0", substitutionHeadName = "ParameterValue")
    public JAXBElement<ExpressionParameter> createExpressionParameter(ExpressionParameter value) {
        return new JAXBElement<ExpressionParameter>(_ExpressionParameter_QNAME, ExpressionParameter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DurationParameter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bpsim.org/schemas/2.0", name = "DurationParameter", substitutionHeadNamespace = "http://www.bpsim.org/schemas/2.0", substitutionHeadName = "ParameterValue")
    public JAXBElement<DurationParameter> createDurationParameter(DurationParameter value) {
        return new JAXBElement<DurationParameter>(_DurationParameter_QNAME, DurationParameter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WeibullDistribution }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bpsim.org/schemas/2.0", name = "WeibullDistribution", substitutionHeadNamespace = "http://www.bpsim.org/schemas/2.0", substitutionHeadName = "ParameterValue")
    public JAXBElement<WeibullDistribution> createWeibullDistribution(WeibullDistribution value) {
        return new JAXBElement<WeibullDistribution>(_WeibullDistribution_QNAME, WeibullDistribution.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GammaDistribution }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bpsim.org/schemas/2.0", name = "GammaDistribution", substitutionHeadNamespace = "http://www.bpsim.org/schemas/2.0", substitutionHeadName = "ParameterValue")
    public JAXBElement<GammaDistribution> createGammaDistribution(GammaDistribution value) {
        return new JAXBElement<GammaDistribution>(_GammaDistribution_QNAME, GammaDistribution.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BinomialDistribution }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bpsim.org/schemas/2.0", name = "BinomialDistribution", substitutionHeadNamespace = "http://www.bpsim.org/schemas/2.0", substitutionHeadName = "ParameterValue")
    public JAXBElement<BinomialDistribution> createBinomialDistribution(BinomialDistribution value) {
        return new JAXBElement<BinomialDistribution>(_BinomialDistribution_QNAME, BinomialDistribution.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TriangularDistribution }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bpsim.org/schemas/2.0", name = "TriangularDistribution", substitutionHeadNamespace = "http://www.bpsim.org/schemas/2.0", substitutionHeadName = "ParameterValue")
    public JAXBElement<TriangularDistribution> createTriangularDistribution(TriangularDistribution value) {
        return new JAXBElement<TriangularDistribution>(_TriangularDistribution_QNAME, TriangularDistribution.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringParameter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bpsim.org/schemas/2.0", name = "StringParameter", substitutionHeadNamespace = "http://www.bpsim.org/schemas/2.0", substitutionHeadName = "ParameterValue")
    public JAXBElement<StringParameter> createStringParameter(StringParameter value) {
        return new JAXBElement<StringParameter>(_StringParameter_QNAME, StringParameter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserDistribution }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bpsim.org/schemas/2.0", name = "UserDistribution", substitutionHeadNamespace = "http://www.bpsim.org/schemas/2.0", substitutionHeadName = "ParameterValue")
    public JAXBElement<UserDistribution> createUserDistribution(UserDistribution value) {
        return new JAXBElement<UserDistribution>(_UserDistribution_QNAME, UserDistribution.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PoissonDistribution }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bpsim.org/schemas/2.0", name = "PoissonDistribution", substitutionHeadNamespace = "http://www.bpsim.org/schemas/2.0", substitutionHeadName = "ParameterValue")
    public JAXBElement<PoissonDistribution> createPoissonDistribution(PoissonDistribution value) {
        return new JAXBElement<PoissonDistribution>(_PoissonDistribution_QNAME, PoissonDistribution.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NumericParameter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bpsim.org/schemas/2.0", name = "NumericParameter", substitutionHeadNamespace = "http://www.bpsim.org/schemas/2.0", substitutionHeadName = "ParameterValue")
    public JAXBElement<NumericParameter> createNumericParameter(NumericParameter value) {
        return new JAXBElement<NumericParameter>(_NumericParameter_QNAME, NumericParameter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TruncatedNormalDistribution }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bpsim.org/schemas/2.0", name = "TruncatedNormalDistribution", substitutionHeadNamespace = "http://www.bpsim.org/schemas/2.0", substitutionHeadName = "ParameterValue")
    public JAXBElement<TruncatedNormalDistribution> createTruncatedNormalDistribution(TruncatedNormalDistribution value) {
        return new JAXBElement<TruncatedNormalDistribution>(_TruncatedNormalDistribution_QNAME, TruncatedNormalDistribution.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParameterValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bpsim.org/schemas/2.0", name = "ParameterValue")
    public JAXBElement<ParameterValue> createParameterValue(ParameterValue value) {
        return new JAXBElement<ParameterValue>(_ParameterValue_QNAME, ParameterValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ErlangDistribution }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bpsim.org/schemas/2.0", name = "ErlangDistribution", substitutionHeadNamespace = "http://www.bpsim.org/schemas/2.0", substitutionHeadName = "ParameterValue")
    public JAXBElement<ErlangDistribution> createErlangDistribution(ErlangDistribution value) {
        return new JAXBElement<ErlangDistribution>(_ErlangDistribution_QNAME, ErlangDistribution.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FloatingParameter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bpsim.org/schemas/2.0", name = "FloatingParameter", substitutionHeadNamespace = "http://www.bpsim.org/schemas/2.0", substitutionHeadName = "ParameterValue")
    public JAXBElement<FloatingParameter> createFloatingParameter(FloatingParameter value) {
        return new JAXBElement<FloatingParameter>(_FloatingParameter_QNAME, FloatingParameter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UniformDistribution }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bpsim.org/schemas/2.0", name = "UniformDistribution", substitutionHeadNamespace = "http://www.bpsim.org/schemas/2.0", substitutionHeadName = "ParameterValue")
    public JAXBElement<UniformDistribution> createUniformDistribution(UniformDistribution value) {
        return new JAXBElement<UniformDistribution>(_UniformDistribution_QNAME, UniformDistribution.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnumParameter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bpsim.org/schemas/2.0", name = "EnumParameter", substitutionHeadNamespace = "http://www.bpsim.org/schemas/2.0", substitutionHeadName = "ParameterValue")
    public JAXBElement<EnumParameter> createEnumParameter(EnumParameter value) {
        return new JAXBElement<EnumParameter>(_EnumParameter_QNAME, EnumParameter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LogNormalDistribution }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bpsim.org/schemas/2.0", name = "LogNormalDistribution", substitutionHeadNamespace = "http://www.bpsim.org/schemas/2.0", substitutionHeadName = "ParameterValue")
    public JAXBElement<LogNormalDistribution> createLogNormalDistribution(LogNormalDistribution value) {
        return new JAXBElement<LogNormalDistribution>(_LogNormalDistribution_QNAME, LogNormalDistribution.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BooleanParameter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bpsim.org/schemas/2.0", name = "BooleanParameter", substitutionHeadNamespace = "http://www.bpsim.org/schemas/2.0", substitutionHeadName = "ParameterValue")
    public JAXBElement<BooleanParameter> createBooleanParameter(BooleanParameter value) {
        return new JAXBElement<BooleanParameter>(_BooleanParameter_QNAME, BooleanParameter.class, null, value);
    }

}
