//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.10 at 02:35:07 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.bpsim.org/schemas/2.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package bpsim;
